// Generated by CoffeeScript 1.6.3
(function() {
  var Action, Attack, Block,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Action = (function() {
    Action.name;

    function Action(performer) {
      this.performer = performer;
    }

    Action.prototype.setPriority = function(priority) {
      this.priority = priority;
    };

    return Action;

  })();

  Attack = (function(_super) {
    __extends(Attack, _super);

    function Attack(attacker, defender) {
      this.attacker = attacker;
      this.defender = defender;
      this.performer = this.attacker;
      this.name = "attack";
    }

    return Attack;

  })(Action);

  Block = (function(_super) {
    __extends(Block, _super);

    function Block(blocker, attacker) {
      this.blocker = blocker;
      this.attacker = attacker;
      this.performer = this.blocker;
      this.name = "block";
    }

    return Block;

  })(Action);

  exports.Attack = Attack;

  exports.Block = Block;

}).call(this);
