// Generated by CoffeeScript 1.6.3
(function() {
  var Damage;

  Damage = (function() {
    function Damage(numberOfRolls, diceSides, modification) {
      this.numberOfRolls = numberOfRolls;
      this.diceSides = diceSides;
      this.modification = modification != null ? modification : 0;
    }

    Damage.prototype.roll = function() {
      var n, sum, _i, _ref;
      sum = 0;
      for (n = _i = 1, _ref = this.numberOfRolls; 1 <= _ref ? _i <= _ref : _i >= _ref; n = 1 <= _ref ? ++_i : --_i) {
        sum += Math.ceil(Math.random() * this.diceSides) + this.modification;
      }
      return sum;
    };

    return Damage;

  })();

  exports.Damage = Damage;

}).call(this);
