// Generated by CoffeeScript 1.6.3
(function() {
  var AgentFactory, Attack, Block, Engine, i, log, loops, results, runBattle, _i;

  AgentFactory = (require('./agent_factory')).AgentFactory;

  Engine = (require('./engine')).Engine;

  Attack = (require('./action')).Attack;

  Block = (require('./action')).Block;

  log = (require('./log')).log;

  results = {
    kristofer: 0,
    mazlach: 0,
    roundLength: 0
  };

  runBattle = function(results) {
    var bothAlive, engine, kristofer, mazlach, roundLength;
    bothAlive = function() {
      return kristofer.isAlive() && mazlach.isAlive();
    };
    roundLength = 0;
    engine = new Engine;
    kristofer = AgentFactory.getKnight("Kristofer");
    mazlach = AgentFactory.getKnight("Mazlach");
    engine.addAgent(kristofer);
    engine.addAgent(mazlach);
    engine.listAgents();
    engine.setupRound();
    engine.addAction(new Attack(kristofer, mazlach));
    engine.addAction(new Attack(kristofer, mazlach));
    engine.addAction(new Attack(kristofer, mazlach));
    engine.addAction(new Block(mazlach, kristofer));
    engine.resolveRound();
    return roundLength++;
    /*
    results.roundLength += roundLength
    
    if kristofer.isAlive()
        results.kristofer += 1
    else if mazlach.isAlive()
        results.mazlach += 1
    else
        results.draw += 1
    */

  };

  loops = 1;

  for (i = _i = 1; 1 <= loops ? _i <= loops : _i >= loops; i = 1 <= loops ? ++_i : --_i) {
    runBattle(results);
  }

  results.roundLength /= loops;

  console.log(results);

}).call(this);
