// Generated by CoffeeScript 1.6.3
(function() {
  var StatusEffect, StatusEffects, StatusEffectsFactory;

  StatusEffect = (function() {
    function StatusEffect(name, duration) {
      this.name = name;
      this.duration = duration;
    }

    StatusEffect.prototype.countDown = function() {
      if (this.duration > 0) {
        return this.duration--;
      }
    };

    StatusEffect.prototype.addToDuration = function(time) {
      return this.duration += time;
    };

    StatusEffect.prototype.isActive = function() {
      return this.duration !== 0;
    };

    StatusEffect.prototype.cure = function() {
      return this.duration = 0;
    };

    return StatusEffect;

  })();

  StatusEffectsFactory = (function() {
    function StatusEffectsFactory() {}

    StatusEffectsFactory.getStunned = function(duration) {
      return new StatusEffect(StatusEffects.stunned, duration);
    };

    StatusEffectsFactory.getDead = function() {
      return new StatusEffect(StatusEffects.dead, -1);
    };

    return StatusEffectsFactory;

  })();

  StatusEffects = {
    stunned: "stunned",
    dead: "dead"
  };

  exports.StatusEffects = StatusEffects;

  exports.StatusEffectsFactory = StatusEffectsFactory;

}).call(this);
